version: "3.7"

services:
  postgresql:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      -  POSTGRES_PASSWORD=root
      -  POSTGRES_USER=root
    volumes:
      - pg_conf:/etc/postgresql
      - pg_log:/var/log/postgresql
      - pg_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"

  guardian:
    container_name: guardian
    build: ./
    ports:
      - "127.0.0.1:80:80"
    env_file:
      - ./.env
    restart: "always"

volumes:
  pg_data:
  pg_conf:
  pg_log:
