version: "3.7"

services:
  postgresql:
    container_name: guardian-pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=resource"
      - "POSTGRES_USER=resource"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - guardian
volumes:
  pg_data:
