version: "3.7"

services:
  postgresql:
    container_name: guardian-pg
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - "POSTGRES_PASSWORD=resource"
      - "POSTGRES_USER=resource"

    volumes:
      - pg_data:/var/lib/postgresql/data
      - init.sql:/docker-entrypoint-initdb.d/init.sql

  guardian:
    container_name: guardian
    build: ./
    ports:
      - "127.0.0.1:80:80"
    env_file:
      - ./.env
    restart: "always"
    depends_on:
      - postgresql

volumes:
  pg_data:
