version: "3.7"

services:
  postgresql:
    container_name: guardian-pg
    image: postgres
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - "POSTGRES_PASSWORD=resource"
      - "POSTGRES_USER=resource"

    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
