name: Deploy Development
on:
  push:
    branches:
      - sentry
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: development
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }} 
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
 